/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/dawei/catkin-ws/src/recycle/laser_assembler/srv/AssembleScans2.srv
 *
 */


#ifndef LASER_ASSEMBLER_MESSAGE_ASSEMBLESCANS2_H
#define LASER_ASSEMBLER_MESSAGE_ASSEMBLESCANS2_H

#include <ros/service_traits.h>


#include <laser_assembler/AssembleScans2Request.h>
#include <laser_assembler/AssembleScans2Response.h>


namespace laser_assembler
{

struct AssembleScans2
{

typedef AssembleScans2Request Request;
typedef AssembleScans2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssembleScans2
} // namespace laser_assembler


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_assembler::AssembleScans2 > {
  static const char* value()
  {
    return "3070b06ce843fd597804874f2df366a3";
  }

  static const char* value(const ::laser_assembler::AssembleScans2&) { return value(); }
};

template<>
struct DataType< ::laser_assembler::AssembleScans2 > {
  static const char* value()
  {
    return "laser_assembler/AssembleScans2";
  }

  static const char* value(const ::laser_assembler::AssembleScans2&) { return value(); }
};


// service_traits::MD5Sum< ::laser_assembler::AssembleScans2Request> should match 
// service_traits::MD5Sum< ::laser_assembler::AssembleScans2 > 
template<>
struct MD5Sum< ::laser_assembler::AssembleScans2Request>
{
  static const char* value()
  {
    return MD5Sum< ::laser_assembler::AssembleScans2 >::value();
  }
  static const char* value(const ::laser_assembler::AssembleScans2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_assembler::AssembleScans2Request> should match 
// service_traits::DataType< ::laser_assembler::AssembleScans2 > 
template<>
struct DataType< ::laser_assembler::AssembleScans2Request>
{
  static const char* value()
  {
    return DataType< ::laser_assembler::AssembleScans2 >::value();
  }
  static const char* value(const ::laser_assembler::AssembleScans2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_assembler::AssembleScans2Response> should match 
// service_traits::MD5Sum< ::laser_assembler::AssembleScans2 > 
template<>
struct MD5Sum< ::laser_assembler::AssembleScans2Response>
{
  static const char* value()
  {
    return MD5Sum< ::laser_assembler::AssembleScans2 >::value();
  }
  static const char* value(const ::laser_assembler::AssembleScans2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_assembler::AssembleScans2Response> should match 
// service_traits::DataType< ::laser_assembler::AssembleScans2 > 
template<>
struct DataType< ::laser_assembler::AssembleScans2Response>
{
  static const char* value()
  {
    return DataType< ::laser_assembler::AssembleScans2 >::value();
  }
  static const char* value(const ::laser_assembler::AssembleScans2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_ASSEMBLER_MESSAGE_ASSEMBLESCANS2_H
